[package]
name = "Rust_Excercise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time =  {version = "0.3", features = ["macros"] }
unicode-reverse = "1.0.8"
